/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecnicassimulacion;

import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author steve
 */
public class ModeloC extends javax.swing.JFrame {

    JComboBox combo = new JComboBox();
    String F1C = "Probabilidad de que cero clientes estén en el sistema";
    String F2C = "Promedio del servidor";
    String F3C = "Número promedio de clientes en la fila de espera";
    String F4C = "tiempo promedio de clientes en el sistema";
    String F5C = "Tiempo promedio de espera en la fila";
    String F6C = "Tiempo promedio transcurrido en el sistema, incluido el servicio";

    Icon iF1C = new ImageIcon(getClass().getResource("/Imagenes/MODC1.PNG"));
    Icon iF2C = new ImageIcon(getClass().getResource("/Imagenes/MODC2.PNG"));
    Icon iF3C = new ImageIcon(getClass().getResource("/Imagenes/MODC3.PNG"));
    Icon iF4C = new ImageIcon(getClass().getResource("/Imagenes/MODC4.PNG"));
    Icon iF5C = new ImageIcon(getClass().getResource("/Imagenes/MODC5.PNG"));
    Icon iF6C = new ImageIcon(getClass().getResource("/Imagenes/MODC6.PNG"));

    /**
     * Creates new form ModeloC
     */
    public ModeloC() {
        initComponents();
        setLocationRelativeTo(null);
        jComboBox1.addItem("Seleccione una opcion");
        jComboBox1.addItem(F1C);
        jComboBox1.addItem(F2C);
        jComboBox1.addItem(F3C);
        jComboBox1.addItem(F4C);
        jComboBox1.addItem(F5C);
        jComboBox1.addItem(F6C);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 146, 191));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULO DE FORMULAS MODELO C");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione lo que desea calcular:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 87, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String datos = (String) jComboBox1.getSelectedItem();

        if (datos.equals(F1C)) {

            //String n = (String) JOptionPane.showInputDialog(null, "Ingrese valor de limite inferior (n)", "MODELO C ", WIDTH, iF1C, null, "");
            String N = (String) JOptionPane.showInputDialog(null, "Ingrese valor de limite superior (N)", "MODELO C ", WIDTH, iF1C, null, "");
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO C ", WIDTH, iF1C, null, "");
            String mu = (String) JOptionPane.showInputDialog(null, "Ingrese valor de μ", "MODELO C ", WIDTH, iF1C, null, "");

            if (N != null && landa != null && mu != null) {
                if (!N.isEmpty() && !landa.isEmpty() && !mu.isEmpty()) {

                    int vn = 0;
                    int vN = Integer.parseInt(N);
                    int vlanda = Integer.parseInt(landa);
                    int vmu = Integer.parseInt(mu);

                    //nuevos
                    //***
                    int vN2 = vN;
                    int vN3 = vN;
                    //****
                    int Factorial1 = 1;
                    int Factorial2 = 1;
                    int valorResta = 0;

                    //primer factorial de N!
                    //    int contador2 = 0;
                    double resultadoDiv1;
                    double resultadoDiv2;
                    double resultadoExpo;
                    double resultadoSuma = 0;
                    double resultadoFinal;

                    //       while (vn<=vN){
                    while (vN2 != 0) {
                        Factorial1 = Factorial1 * vN2;
                        vN2--;

                    }

                    while (vn <= vN3) {
                        valorResta = vN3 - vn;

                        while (valorResta != 0) {

                            Factorial2 = Factorial2 * valorResta;
                            valorResta--;

                        }

                        resultadoDiv1 = Factorial1 / Factorial2;
                        resultadoDiv2 = (double) vlanda / vmu;
                        resultadoExpo = resultadoDiv1 * Math.pow(resultadoDiv2, vn);
                        resultadoSuma = resultadoSuma + resultadoExpo;
                        resultadoFinal = 1 / resultadoSuma;

                        Factorial2 = 1;

                        vn++;

                    }
                    resultadoFinal = 1 / resultadoSuma;
                    DecimalFormat formato = new DecimalFormat("#.####");

                    JOptionPane.showMessageDialog(null, "El resultado de la formula es: " + formato.format(resultadoFinal));
                }
            }else
            JOptionPane.showMessageDialog(null, "valores nulos");

        }

        if (datos.equals(F2C)) {
            String p0 = (String) JOptionPane.showInputDialog(null, "Ingrese valor de Po", "MODELO C ", WIDTH, iF2C, null, "");

            if (p0 != null) {
                if (!p0.isEmpty()) {

                    double vp0 = Double.valueOf(p0);
                    double p = 1 - vp0;

                    JOptionPane.showMessageDialog(null, "El promedio del servidor es = " + p);
                }
            }
            JOptionPane.showMessageDialog(null, "valores nulos");
        }

        if (datos.equals(F3C)) {
            {
                String n = (String) JOptionPane.showInputDialog(null, "Ingrese valor de N", "MODELO B ", WIDTH, iF3C, null, "");
                String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO B ", WIDTH, iF3C, null, "");
                String mu = (String) JOptionPane.showInputDialog(null, "Ingrese valor de μ", "MODELO B ", WIDTH, iF3C, null, "");
                String p0 = (String) JOptionPane.showInputDialog(null, "Ingrese valor de P0", "MODELO B ", WIDTH, iF3C, null, "");

                if (landa != null && mu != null && n != null && p0 != null) {
                    if (!landa.isEmpty() && !mu.isEmpty() && !n.isEmpty() && !p0.isEmpty()) {

                        double vlanda = Double.valueOf(landa);
                        double vmu = Double.valueOf(mu);
                        double vp0 = Double.valueOf(p0);
                        double vn = Double.valueOf(n);

                        double ej3 = vn - ((vlanda + vmu) / vlanda) * (1 - vp0);

                        JOptionPane.showMessageDialog(null, "Número promedio de clientes en la fila de espera es de = " + ej3);
                    }
                }else
                                JOptionPane.showMessageDialog(null, "valores nulos");

            }

        }

        if (datos.equals(F4C)) {
            String n = (String) JOptionPane.showInputDialog(null, "Ingrese valor de N", "MODELO C ", WIDTH, iF4C, null, "");
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO C ", WIDTH, iF4C, null, "");
            String mu = (String) JOptionPane.showInputDialog(null, "Ingrese valor de μ", "MODELO C ", WIDTH, iF4C, null, "");
            String p0 = (String) JOptionPane.showInputDialog(null, "Ingrese valor de P0", "MODELO C ", WIDTH, iF4C, null, "");

            if (landa != null && mu != null && n != null && p0 != null) {
                if (!landa.isEmpty() && !mu.isEmpty() && !n.isEmpty() && !p0.isEmpty()) {

                    double vlanda = Double.valueOf(landa);
                    double vmu = Double.valueOf(mu);
                    double vp0 = Double.valueOf(p0);
                    double vn = Double.valueOf(n);

                    double ej4 = vn - (vmu / vlanda) * (1 - vp0);

                    JOptionPane.showMessageDialog(null, "Tiempo promedio de clientes en el sistema es de = " + ej4);

                }else
                                JOptionPane.showMessageDialog(null, "valores nulos");

            }

        }

        if (datos.equals(F5C)) {

            String Lq = (String) JOptionPane.showInputDialog(null, "Ingrese valor de Lq", "MODELO C ", WIDTH, iF5C, null, "");
            String n = (String) JOptionPane.showInputDialog(null, "Ingrese valor de N", "MODELO C ", WIDTH, iF5C, null, "");
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO C ", WIDTH, iF5C, null, "");
            String L = (String) JOptionPane.showInputDialog(null, "Ingrese valor de L", "MODELO C ", WIDTH, iF5C, null, "");

            if (landa != null && Lq != null && n != null && L != null) {
                if (!landa.isEmpty() && !Lq.isEmpty() && !n.isEmpty() && !L.isEmpty()) {

                    double vlanda = Double.valueOf(landa);
                    double vL = Double.valueOf(L);
                    double vlq = Double.valueOf(Lq);
                    double vn = Double.valueOf(n);

                    double ej5 = (vlq * (1 / ((vn - vL) * vlanda)));

                    JOptionPane.showMessageDialog(null, "Tiempo promedio de espera en la fila es de = " + ej5);

                }
            }else
            JOptionPane.showMessageDialog(null, "valores nulos");

        }
        if (datos.equals(F6C)) {

            String L = (String) JOptionPane.showInputDialog(null, "Ingrese valor de L", "MODELO C ", WIDTH, iF6C, null, "");
            String n = (String) JOptionPane.showInputDialog(null, "Ingrese valor de N", "MODELO C ", WIDTH, iF6C, null, "");
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO C ", WIDTH, iF6C, null, "");

            if (landa != null && L != null && n != null) {
                if (!landa.isEmpty() && !L.isEmpty() && !n.isEmpty()) {

                    double vlanda = Double.valueOf(landa);
                    double vL = Double.valueOf(L);
                    double vn = Double.valueOf(n);

                    double ej6 = (vL * (1 / ((vn - vL) * vlanda)));

                    JOptionPane.showMessageDialog(null, "Tiempo promedio transcurrido en el sistema, incluido el servicio es de = " + ej6);

                }
            }else
            JOptionPane.showMessageDialog(null, "valores nulos");

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeloC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
